# Generated by Django 2.2.6 on 2020-01-23 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='published',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
