# Generated by Django 2.2.6 on 2020-01-20 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutoriallanguage',
            options={'verbose_name_plural': 'Languages'},
        ),
    ]
