# Generated by Django 2.2.6 on 2020-01-20 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_auto_20200120_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoriallanguage',
            name='summary',
        ),
    ]
