# Generated by Django 2.2.6 on 2020-01-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_auto_20200120_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialcategory',
            name='language',
        ),
        migrations.DeleteModel(
            name='TutorialLanguage',
        ),
    ]
