# Generated by Django 2.2.6 on 2020-01-23 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_news_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
